-- Operational map coordinates (Phase 1)
ALTER TABLE "floors" ADD COLUMN IF NOT EXISTS "mapViewBox" TEXT NOT NULL DEFAULT '0 0 1000 600';
ALTER TABLE "floors" ADD COLUMN IF NOT EXISTS "layoutSvg" TEXT;

ALTER TABLE "zones" ADD COLUMN IF NOT EXISTS "mapX" DOUBLE PRECISION;
ALTER TABLE "zones" ADD COLUMN IF NOT EXISTS "mapY" DOUBLE PRECISION;
ALTER TABLE "zones" ADD COLUMN IF NOT EXISTS "mapWidth" DOUBLE PRECISION;
ALTER TABLE "zones" ADD COLUMN IF NOT EXISTS "mapHeight" DOUBLE PRECISION;

ALTER TABLE "checkpoints" ADD COLUMN IF NOT EXISTS "mapX" DOUBLE PRECISION;
ALTER TABLE "checkpoints" ADD COLUMN IF NOT EXISTS "mapY" DOUBLE PRECISION;
