ALTER TABLE "floors" ADD COLUMN IF NOT EXISTS "layoutImageUrl" TEXT;
ALTER TABLE "floors" ADD COLUMN IF NOT EXISTS "layoutWidth" INTEGER;
ALTER TABLE "floors" ADD COLUMN IF NOT EXISTS "layoutHeight" INTEGER;
